
:NAME:      Audio archivering
:MEDIA:     :AUDIO
:QUALITY:   :ARCHIVE

:MANIFESTATIONS:

  - :MANIFESTATION:   ARCHIVE
    :FORMAT:          :WAV

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :MP3

  - :MANIFESTATION:   VIEW
    :FORMAT:          :MP3

