
:NAME:      Documenten hoge kwaliteit
:MEDIA:     :DOCUMENT
:QUALITY:   :HIGH

:MANIFESTATIONS:

  - :MANIFESTATION:   ARCHIVE
    :FORMAT:          :PDFA

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :PDF

  - :MANIFESTATION:   THUMBNAIL
    :FORMAT:          :JPEG
    :OPTIONS:
      :RESIZE:        107x150
      :QUALITY:       50%

