
NAME:      Documenten archivering
MEDIA:     :DOCUMENT
QUALITY:   :ARCHIVE

MANIFESTATIONS:

  - MANIFESTATION:   VIEW
    FORMAT:          :PDF

  - MANIFESTATION:   VIEW_MAIN
    FORMAT:          :PDF

  - MANIFESTATION:   THUMBNAIL
    FORMAT:          :JPEG
    OPTIONS:
      RESIZE:        107x150
      QUALITY:       50%

