
:NAME:      Afbeeldingen archivering cag
:MEDIA:     :IMAGE
:QUALITY:   :CAG

:MANIFESTATIONS:

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :JPEG
    :OPTIONS:
      :RESAMPLE:      75

  - :MANIFESTATION:   THUMBNAIL
    :FORMAT:          :JPEG
    :OPTIONS:
      :RESIZE:        500
      :QUALITY:       50%

