
NAME:      Afbeeldingen archivering
MEDIA:     :IMAGE
QUALITY:   :ARCHIVE

MANIFESTATIONS:

  - MANIFESTATION:   VIEW_MAIN
    FORMAT:          :JPEG
    OPTIONS:
      SCALE:         80%
      QUALITY:       70%

  - MANIFESTATION:   VIEW
    FORMAT:          :JPEG2000

  - MANIFESTATION:   THUMBNAIL
    FORMAT:          :JPEG
    OPTIONS:
      RESIZE:        107x150
      QUALITY:       50%

