
:NAME:      Afbeeldingen archivering europeana
:MEDIA:     :IMAGE
:QUALITY:   :EUROPEANA

:MANIFESTATIONS:

  - :MANIFESTATION:   ARCHIVE
    :FORMAT:          :TIFF

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :JPEG
    :OPTIONS:
      :SCALE:         80%
      :QUALITY:       70%

  - :MANIFESTATION:   VIEW
    :FORMAT:          :JPEG2000

  - :MANIFESTATION:   THUMBNAIL
    :FORMAT:          :JPEG
    :OPTIONS:
      :RESIZE:        200
      :QUALITY:       50%

