
:NAME:      mp3
:MEDIA:     :AUDIO
:QUALITY:   :KADOC

:MANIFESTATIONS:

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :MP3

  - :MANIFESTATION:   THUMBNAIL
    :FORMAT:          :JPEG
    :OPTIONS:
      :RESIZE:        107x150
      :QUALITY:       50%
