
:NAME:      Video archivering
:MEDIA:     :AUDIO
:QUALITY:   :ARCHIVE

:MANIFESTATIONS:

  - :MANIFESTATION:   ARCHIVE
    :FORMAT:          :MJPEG2000

  - :MANIFESTATION:   VIEW_MAIN
    :FORMAT:          :FLASH
    :OPTIONS:
      :SCALE:         50%
      :QUALITY:       70%

  - :MANIFESTATION:   VIEW
    :FORMAT:          :FLASH

