
NAME:      Video hoge kwaliteit
MEDIA:     :VIDEO
QUALITY:   :HIGH

MANIFESTATIONS:

  - MANIFESTATION:   VIEW_MAIN
    FORMAT:          :FLASH
    OPTIONS:
      SCALE:         50%
      QUALITY:       70%

  - MANIFESTATION:   VIEW
    FORMAT:          :FLASH

