:MEDIA:         :ARCHIVE
:TYPES:
  - :TYPE:        :TAR
    :MIME:        application/x-tar
    :EXTENSIONS:  tar
  - :TYPE:        :ZIP
    :MIME:        application/zip
    :EXTENSIONS:  zip
  - :TYPE:        :TGZ
    :MIME:        application/x-compressed
    :EXTENSIONS:  tgz