:MEDIA:         :DOCUMENT
:TYPES:
  - :TYPE:          :PDF
    :MIME:          application/pdf
    :EXTENSIONS:    pdf
  - :TYPE:          :PDFA
    :MIME:          application/pdfa
    :EXTENSIONS:    pdfa
